name: commit

on: [pull_request,push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run command
        run: node convert-to-json.js
      - name: exho
        run: echo 'running'

